version: "3.7"

services:
  jenplane:
    build:
      context: ../backend/
      dockerfile: Dockerfile
    container_name: jenplane-api
    image: jenplane-api
    restart: unless-stopped
    env_file:
      - ../backend/.env
    ports:
      - "0.0.0.0:5000:80"
    depends_on:
      - mongodb
    networks:
      - frontend
      - backend
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db
    env_file:
      - ../backend/.env
    networks:
      - backend
  frontend:
    container_name: jenplane-frontend
    build:
      context: ../frontend/
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3000:80"

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
volumes:
  mongodbdata:
    driver: local
